[ new ] Better output test runner for panics

diff --git a/tests/run b/tests/run
--- a/tests/run
+++ b/tests/run
@@ -2,6 +2,16 @@
 
 set -eu
 
+if true || test -t 1; then
+   SUCCESS="\e[32mSUCCESS\e[0m"
+   FAILURE="\e[31mFAILURE\e[0m"
+   PANIC="\e[34mPANIC\e[0m"
+else
+   SUCCESS="SUCCESS"
+   FAILURE="FAILURE"
+   PANIC="PANIC"
+fi
+
 readonly DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 readonly BUILD="$DIR/../build/"
 mkdir -p $BUILD
@@ -12,23 +22,24 @@ if [ ! -d "$SCALADIR" ]; then
     exit 1
 fi
 
-readonly SUNSHINE="$DIR/../bin/org.metaborg.sunshine2-2.5.2.jar"
-if [ ! -f "$SUNSHINE" ]; then
-    echo "FAILURE: Cannot find file $SUNSHINE"
+readonly SUNSHINE_JAR="$DIR/../bin/org.metaborg.sunshine2-2.5.2.jar"
+if [ ! -f "$SUNSHINE_JAR" ]; then
+    printf "[$PANIC] Cannot find file $SUNSHINE_JAR\n"
     exit 1
 fi
 
-readonly ATERM="java -jar $SUNSHINE parse -l $SCALADIR -p . -i"
+readonly SUNSHINE="java -jar $SUNSHINE_JAR"
 
-if true || test -t 1; then
-   SUCCESS="\e[32mSUCCESS\e[0m"
-   FAILURE="\e[31mFAILURE\e[0m"
-   PANIC="\e[34mPANIC\e[0m"
-else
-    SUCCESS="SUCCESS"
-    FAILURE="FAILURE"
-    PANIC="PANIC"
+statix check -I $DIR/../src/ scala 2>&1
+stx_runs=${PIPESTATUS[0]}
+if [ ! $stx_runs ]; then
+    printf "[$PANIC] Cannot run statix\n"
+    exit 1
 fi
+
+function expect {
+    if [ $1 -eq 0 ]; then printf "pass"; else printf "fail"; fi
+}
 
 function agree {
     [ $1 -eq 0 -a $2 -eq 0 ] || [ $1 -ne 0 -a $2 -ne 0 ]
@@ -36,26 +47,29 @@ function agree {
 
 for infile in "$@"
 do
-    if ! (echo $infile | grep -s "no.scala") 
+    testname="${infile%.java}"
+
+    if ! (echo "$testname" | grep -s "\.no")
     then
         positive=0
-	echo "Expect pass"
     else
         positive=1
-	echo "Expect fail"
     fi
-
-    # make sure to remove all class files to avoid incidental capture
-    rm -f $(dirname "$infile")/*.class
+    echo "Expect $(expect $positive)"
 
     # run scala compiler
     scalac -d $BUILD $infile 2>&1 | tee ${infile%.scala}.scalac.out 
     scala_ok=${PIPESTATUS[0]}
+    echo "scalac $(expect $scala_ok)"
+    if ! agree $scala_ok $positive; then
+        printf "[$PANIC:DISAGREE] $infile\n"
+        continue
+    fi
 
     # compile the file to an aterm
     sca=${infile%.scala}.sca3
     cp "$infile" $sca
-    ${ATERM} $sca > ${infile%.scala}.aterm 2> /dev/null || {
+    ${SUNSHINE} parse -l "${SCALADIR}" -p . -i "$sca" > ${infile%.scala}.aterm 2> /dev/null || {
         printf "[$PANIC:PARSING] $infile\n"
         continue
     }
@@ -63,11 +77,11 @@ do
     # run statix on the aterm
     statix check -I $DIR/../src/ scala ${infile%.scala}.aterm 2>&1 | tee ${infile%.scala}.stx.out
     stx_ok=${PIPESTATUS[0]}
-    
+
     # compute test result by comparison
     if [ $stx_ok -eq 65 ]; then
         printf "[$PANIC:STUCK] $infile\n"
-    elif agree $stx_ok $scala_ok && agree $scala_ok $positive; then
+    elif agree $stx_ok $positive; then
         printf "[$SUCCESS] $infile\n"
     else
         printf "[$FAILURE] $infile\n"
